### ISSUE TITLE
Cloudflare部署错误

### ISSUE THREAD

**Issue by Draculabo** [x-dr/chatgptProxyAPI#10]
我在《利用Cloudflare pages部署》的第五步《点击Save and Deploy部署》出现了如下错误，我应该怎么解决它？
![image](https://user-images.githubusercontent.com/49336820/227886892-7ebe14a1-060a-41d9-968b-f95482c732a3.png)
下面是我的配置：
![image](https://user-images.githubusercontent.com/49336820/227887193-ec57eb92-e3e0-4b2b-a14f-36d00cb76c1d.png)

**Comment by x-dr** [comment]
你有修改过什么吗？我部署时没问题；你试试重新部署看看
![image](https://user-images.githubusercontent.com/79109673/227923125-6da6fdc6-abb6-4f59-97fc-c56bd5150304.png)
![image](https://user-images.githubusercontent.com/79109673/227923195-f40e9c90-c798-4e78-b75d-7e38f2dbca49.png)
