### ISSUE TITLE
cloudflare worker 100秒超时，pages也是吗，我想知道怎么把timeout设置长一点。

### ISSUE THREAD

**Issue by sanbaideng** [x-dr/chatgptProxyAPI#11]
gpt-4慢一点，访问经常返回524错误，是cloudflare的超时，
cloudflare一般用户只能到100秒->https://developers.cloudflare.com/support/troubleshooting/cloudflare-errors/troubleshooting-cloudflare-5xx-errors/#error-524-a-timeout-occurred
有精通的大佬吗，怎么把timeout设置长一点

**Comment by x-dr** [comment]
cloudflare免费用户的话应该最大只能100秒了，企业账号有600秒

**Comment by zhuqingcode** [comment]
我按照你的方法做了一遍，不行
