### ISSUE TITLE
用docker部署的，直接ip：port/proxy/v1这样调用 发现不支持流

### ISSUE THREAD

**Issue by yaocccc** [x-dr/chatgptProxyAPI#15]

**Comment by x-dr** [comment]
确实是不支持 你可以试一下用cloudflare部署，或者看看这一个项目[easychen/openai-api-proxy](https://github.com/easychen/openai-api-proxy)

**Comment by yaocccc** [comment]
okk，感谢，我使用了阿里云的func调用布的，ok了
