### ISSUE TITLE
打开xxxxxxxx.pages.dev/v1/chat/completions ，网页是404

### ISSUE THREAD

**Issue by ziyou2** [x-dr/chatgptProxyAPI#21]
打开xxxxxxxx.pages.dev/v1/chat/completions ，网页是404

**Comment by x-dr** [comment]
你是怎样部署的我不知道，无法判断错误，而且你不是已经部署好了吗？

<img width="866" alt="image" src="https://user-images.githubusercontent.com/79109673/231461701-c7eec847-b53b-4c2a-8340-2fffab3045f6.png">
