### ISSUE TITLE
利用Cloudflare Worker中转api.openai.com方式，正常访问提示超时，挂🪜就可以

### ISSUE THREAD

**Issue by izsm** [x-dr/chatgptProxyAPI#22]
利用Cloudflare Worker中转api.openai.com方式，正常访问提示超时，挂🪜就可以，然后使用你的演示地址不挂🪜也是正常的，请问下这是什么问题？
我的域名是从阿里云新申请的，DNS修改成Cloudflare的之后，域名解析检测提示如下，不知道跟这个有没有关系
<img width="720" alt="截屏2023-04-13 09 33 19" src="https://user-images.githubusercontent.com/20026815/231623638-49eaa566-3c37-45a7-a4c4-634177c7ca42.png">

**Comment by x-dr** [comment]
你域名接入Cloudflare时没配置好吧，或者你可以试一下用Cloudflare pages 这个不用绑定域名也可以

**Comment by IwfWcf** [comment]
@x-dr 遇到同样的问题，测试后发现把域名的 NS 改成 Cloudflare 的之后在 Cloudflare 设置的 dns 解析记录没有生效。这个一般需要多长时间才会生效？
