### ISSUE TITLE
在最后部署好生成的静态网站上查询SK-xxx需要输入的登陆信息是什么?

### ISSUE THREAD

**Issue by bernardatgh** [x-dr/chatgptProxyAPI#29]
请教一下, 如在已经部署好的静态网站上, 查询sk使用量的界面  输入API的sk查询后, 提示框弹出需要查询的登陆用户名和密码? 请问这个在哪里设置的, 默认是什么, 谢谢!
https://xxxx.pages.dev/
![image](https://user-images.githubusercontent.com/11673998/233917348-026b2a9a-316a-4eb3-a01c-41fe6ad369fd.png)

**Comment by x-dr** [comment]
这是因为你输入的key已失效，你点取消就会显示具体原因了。

**Comment by bernardatgh** [comment]
thanks
