### ISSUE TITLE
创建好以后，反代后地址还是无法访问

### ISSUE THREAD

**Issue by JohnGao818** [x-dr/chatgptProxyAPI#3]
用的系统分配的默认域名，国内还是无法访问
https://polished-fire-c950.chat-john.workers.dev/v1/chat/completions

**Comment by x-dr** [comment]
要配置域名才行，workers.dev被墙了

**Comment by JohnGao818** [comment]
> 要配置域名才行，workers.dev被墙了

那还要注册域名，太麻烦了
