### ISSUE TITLE
大家都用着没问题吗？

### ISSUE THREAD

**Issue by ymli1981** [x-dr/chatgptProxyAPI#31]
有个问题是只能用自定义域名，然后这个域名必须被它托管，被它dns解析后国内访问不稳定，经常链接不上。
大家都没遇到这个问题吗？

**Comment by ymli1981** [comment]
教程要赞一个，写得非常详细，小白部署毫无压力

**Comment by liuhuapiaoyuan** [comment]
同样有丢包的可能。。。

**Comment by stql-xyz** [comment]
> ？
我刚遇到、有时候链接不上。 多弄几个域名切换着用会不会好一点。

**Comment by xingziyang** [comment]
使用cloudflare_proxy_pages.md，这个文件中描述的方案部署出现如下错误，请问如何解决？

**Comment by xingziyang** [comment]
使用cloudflare_proxy_pages.md，这个文件中描述的方案部署出现如下错误，请问如何解决？
{
error: {
message: "Invalid URL (GET /)",
type: "invalid_request_error",
param: null,
code: null
}
}

**Comment by x-dr** [comment]
@xingziyang 请用官方api的示例参数请求

**Comment by xingziyang** [comment]
> @xingziyang 请用官方api的示例参数请求

好的，现在是可以了，原因是：使用cloudflare page生成的域名不稳定，有时可以访问有时不可以，这个问题大佬可以解释一下吗？

**Comment by 1464616601** [comment]
2、使用CloudFlare Pages进行中转
然后报这个
  "error": {
    "message": "Invalid URL (POST /api/v1/chat/completions)",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
请问是什么原因

**Comment by 1464616601** [comment]
> 

已经解决，第二点的不用加/api
