### ISSUE TITLE
已经按照第2种方法设置好cloudfare的page，后续怎样使用访问openai?

### ISSUE THREAD

**Issue by canshen1234** [x-dr/chatgptProxyAPI#36]
第2种方法，然后用python按照用法里面的python运行，出现错误，使用的是自己的key。

**Comment by x-dr** [comment]
### **提问的智慧**

[使用有意义且明确的主题](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way#%E4%BD%BF%E7%94%A8%E6%9C%89%E6%84%8F%E4%B9%89%E4%B8%94%E6%98%8E%E7%A1%AE%E7%9A%84%E4%B8%BB%E9%A2%98)
