### ISSUE TITLE
安装第3种方法，打开https://xxx.xxx/api报以下错误

### ISSUE THREAD

**Issue by 13416157913** [x-dr/chatgptProxyAPI#37]
Error: Could not access built-in Node.js modules. Please make sure that your Cloudflare Pages project has the 'nodejs_compat' compatibility flag set.

**Comment by x-dr** [comment]
NODE_VERSION是否是16？ cloudflare pages 的Edge Runtime 要node 16才支持

**Comment by markwhitey** [comment]
我也是  NODE_VERSION 也设置的node 16

**Comment by x-dr** [comment]
> 我也是 NODE_VERSION 也设置的node 16

方便截一下构建配置的图看看吗

**Comment by x-dr** [comment]
> 我也是 NODE_VERSION 也设置的node 16

知道了，是cloudflare/next-on-pages的版本问题

`Build command` 设置为 `npx @cloudflare/next-on-pages@pre-v1 --experimental-minify` 即可

```
npx @cloudflare/next-on-pages@pre-v1 --experimental-minify
```

![image](https://github.com/x-dr/chatgptProxyAPI/assets/79109673/bac0ea0b-60fd-45a6-8066-0a270b83f62f)
