### ISSUE TITLE
想问下这个走cloudflare与购买静态美国住宅代理IP有什么区别？

### ISSUE THREAD

**Issue by shumintao** [x-dr/chatgptProxyAPI#46]
这个的作用是什么？难道就是翻墙下 ？

**Comment by walkchen9** [comment]
这个不用魔法，直接能调用api，不用翻墙

**Comment by shumintao** [comment]
> 这个不用魔法，直接能调用api，不用翻墙

哦哦哦

**Comment by x-dr** [comment]
> > 这个不用魔法，直接能调用api，不用翻墙
> 
> 哦哦哦，大家都用这个吗 ？稳定吗 ？大批量调用有问题吗 ？

除了慢了点外，挺稳定的
