### ISSUE TITLE
可否使用2个本项目代理调用openai api？

### ISSUE THREAD

**Issue by walkchen9** [x-dr/chatgptProxyAPI#47]
办公环境本地电脑完全没有互联网权限；
本人已经在vercel里部署了本项目代理，并绑定了域名，正常使用。

因内部电脑无法访问互联网，我想请教一下，能否在可访问互联网的服务器上，搭建一个代理，并将openai的相关域名指向vercel部署的代理上，以此解决电脑能正常使用api接口？
相当于使用了2个api代理。

如果不可以，是否有其他建议？谢谢！

**Comment by x-dr** [comment]
你内部电脑无法访问互联网，那你就无法访问互联网的服务器，所以无解

**Comment by walkchen9** [comment]
内部电脑无法访问互联网，但是有一台服务器可以访问互联网，也与办公电脑互通

所以我想能不能在那台可上访问互联网的服务器搭一个api代理，指向Vercel部署的页面
这样相当于使用2个这个api代理，不知是否可行？

**Comment by x-dr** [comment]
可以，你直接在可以访问互联网的服务器搭建服务用内网机器访问不是更方便？
