### ISSUE TITLE
使用CloudFlare Pages进行中转，通过自定义域的方式遇到报错

### ISSUE THREAD

**Issue by valium123** [x-dr/chatgptProxyAPI#48]
使用CloudFlare自带的域名 可以正常访问  使用自定义域的域名在没挂梯子时会报错，挂了梯子正常

报错信息如下
openai.error.APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接
。', None, 10054, None))
麻烦作者看一下，盼复

**Comment by x-dr** [comment]
信息太少，估计是网络问题

**Comment by Newaiguy** [comment]
昨天之前还能用，昨天开始用不了了，有v1那个请求好像不行了，有解决办法吗？

**Comment by x-dr** [comment]
> 昨天之前还能用，昨天开始用不了了，有v1那个请求好像不行了，有解决办法吗？

没问题吧，我建的[https://openai.451024.xyz/](https://openai.451024.xyz/)一直在用没问题啊！

**Comment by Newaiguy** [comment]
找到原因了，是程序打包的问题，不知道为什么作为全局变量不行，作为函数内部参数就行了发自我的手机-------- 原始邮件 --------发件人： x-dr ***@***.***>日期： 2023年7月10日周一 半夜11:41收件人： x-dr/chatgptProxyAPI ***@***.***>抄送： Newaiguy ***@***.***>, Comment ***@***.***>主    题： Re: [x-dr/chatgptProxyAPI] 使用CloudFlare Pages进行中转，通过自定义域的方式遇到报错 (Issue #48)

昨天之前还能用，昨天开始用不了了，有v1那个请求好像不行了，有解决办法吗？

没问题吧，我建的https://openai.451024.xyz/一直在用没问题啊！
