### ISSUE TITLE
按照你的js代码贴到左边，出现了404，该怎么处理？

### ISSUE THREAD

**Issue by frankchn-x** [x-dr/chatgptProxyAPI#5]
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/124376835/224719445-3c34beb5-ee08-43d6-830b-92732152e265.png">

**Comment by x-dr** [comment]
这是正常的，要post 请求请求头带key 请认真看说明
![image](https://user-images.githubusercontent.com/79109673/224762021-f1f4481b-0102-4aff-b065-a5fdea7cd31e.png)
