### ISSUE TITLE
无效

### ISSUE THREAD

**Issue by luoysuan** [x-dr/chatgptProxyAPI#56]
我按照教程用pages搭建的转发好像没效果，能帮忙看看什么原因吗
这个是复制的代码
https://github.com/luoysuan/Forwarding/blob/main/_worker.js

下面的是cloudflare的设置
![image](https://github.com/x-dr/chatgptProxyAPI/assets/51365362/83dcc198-0e8c-4486-8198-52cbfff6aa9f)

下面是使用revchatGpt的代码
![image](https://github.com/x-dr/chatgptProxyAPI/assets/51365362/32059065-8dc4-4ba5-a759-e936cc6c5e35)

报错
![image](https://github.com/x-dr/chatgptProxyAPI/assets/51365362/83fe9f2e-a496-4a09-a426-e3c0ef8ef999)

**Comment by x-dr** [comment]
只支持官方的key,不支持cookie
