### ISSUE TITLE
Sorry, you have been blocked

### ISSUE THREAD

**Issue by hohuiking** [x-dr/chatgptProxyAPI#57]
cf带了来源ip过去openai，应该被openai那边封了cf过来的。有没有办法抹去来源ip？
![WX20231116-131256](https://github.com/x-dr/chatgptProxyAPI/assets/23737203/b87f993d-9dc6-4578-b2d8-efcd1866b224)

**Comment by wlh928043590** [comment]
请问解决了吗 遇到一样的问题

**Comment by coloz** [comment]
一样的问题

**Comment by ymli1981** [comment]
是要更换节点吗

**Comment by x-dr** [comment]
cloudflare没带来源ip过去openai，估计是openai那边禁用了;有空我试试vercel看看能用不

**Comment by wlh928043590** [comment]
> cloudflare没带来源ip过去openai，估计是openai那边禁用了;有空我试试vercel看看能用不

试了下vercel 可以了

**Comment by Aiurvie** [comment]
同样的问题。
等待进一步发展

**Comment by Subdue0** [comment]
> > cloudflare没带来源ip过去openai，估计是openai那边禁用了;有空我试试vercel看看能用不
> 
> 试了下vercel 可以了

把梯子关了

**Comment by hohuiking** [comment]
> cloudflare没带来源ip过去openai，估计是openai那边禁用了;有空我试试vercel看看能用不

好像vercel也把ip传过去了
[https://github.com/Yidadaa/ChatGPT-Next-Web/issues/3286](https://github.com/Yidadaa/ChatGPT-Next-Web/issues/3286)

**Comment by Aiurvie** [comment]
心态爆炸，刚开通 Plus，还没捂热，就迎来了封号邮件。

**Comment by ymli1981** [comment]
亲测阿里云函数可用。转载教程：https://simonmy.com/posts/%E4%BD%BF%E7%94%A8%E9%98%BF%E9%87%8C%E4%BA%91%E5%87%BD%E6%95%B0%E8%AE%A1%E7%AE%97%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86openai%E6%9C%8D%E5%8A%A1.html

**Comment by Subdue0** [comment]
我去掉的cf本身的cdn功能改用aws的境外cdn，已经搞定了，但配置aws的境外cdn备用域名出了点问题，不知道为什么配置了也没用，现在只能用随机域名了，延迟在200ms左右。

**Comment by x-dr** [comment]
用cloudflare pages 可以 cloudflare Workers 被ban了

**Comment by x-dr** [comment]
好像又可以用了，我用腾讯云境内服务器正常使用。
