### ISSUE TITLE
还是提示连接错误，但是请求是发送到cloudflare的，奇奇怪怪

### ISSUE THREAD

**Issue by yaya6630170** [x-dr/chatgptProxyAPI#58]
![image](https://github.com/x-dr/chatgptProxyAPI/assets/72657813/017df594-9f7d-4f17-b733-565b6b055e69)
![image](https://github.com/x-dr/chatgptProxyAPI/assets/72657813/67a9b058-f960-440e-9ac6-9aecb180fe64)
进到路由的网址里一看，怎么是个这个东西![image](https://github.com/x-dr/chatgptProxyAPI/assets/72657813/0d491956-a4dd-4682-9526-87382d74125d)？？？

**Comment by yaya6630170** [comment]
这个猫是个什么东西，是OpenAI返回来搞人的么~

**Comment by yaya6630170** [comment]
![image](https://github.com/x-dr/chatgptProxyAPI/assets/72657813/da7a2bc4-5cbe-422f-b780-db269d232296)
从这进去看的

**Comment by x-dr** [comment]
这个项目是反代https://api.openai.com/ ，openai给什么就返回什么；至于提示连接错误那是你的问题
