### ISSUE TITLE
域名地区问题

### ISSUE THREAD

**Issue by LokerL** [x-dr/chatgptProxyAPI#7]
你好，请问最后绑定的自己的域名需要时国外注册的吗？
还是说国内注册的就可以，如阿里云腾讯云注册并备案的域名

**Comment by LokerL** [comment]
或者怎么知道自己的域名有没有被GFW墙呢

**Comment by x-dr** [comment]
> 或者怎么知道自己的域名有没有被GFW墙呢

建议百度
