### ISSUE TITLE
已按照这个代码搭建好了，欢迎大家使用，🤭 ：https://openai.proxy.mailjob.net

### ISSUE THREAD

**Issue by jefferyjob** [x-dr/chatgptProxyAPI#9]
<img width="949" alt="ea238c1a7c3a77c17a1756719a5c8b9" src="https://user-images.githubusercontent.com/24731115/226522240-cc42d97f-6220-45b3-8bae-30c5ccaf5cd5.png">

**Comment by zhanghaok** [comment]
请问怎么请求参数啊，能说一下吗，我如何使用Java程序使用这个API

**Comment by jefferyjob** [comment]
使用post调用就可以，你哪里有问题呢？

**Comment by he15his** [comment]
postman没问题，用python调报错 429 Client Error: Too Many Requests for url

**Comment by zhanghaok** [comment]
一样一样 我也是python调用有问题




板蓝根
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "x-dr/chatgptProxyAPI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月6日(星期四) 下午5:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [x-dr/chatgptProxyAPI] 已按照这个代码搭建好了，欢迎大家使用，🤭 ：https://openai.proxy.mailjob.net (Issue #9)





 
postman没问题，用python调报错 429 Client Error: Too Many Requests for url

**Comment by jefferyjob** [comment]
那就是代码写的有问题，理论上postman可以调用通，说明服务没有问题

我这边是go语言调用的，倒是没有py的示例

**Comment by jefferyjob** [comment]
> 

什么修改默认页面？？
这只是个反向代理的地址，具体页面的搭建需要你自己实现
